### ISSUE TITLE
cannot change timezone of root fcrontab

### ISSUE THREAD

**Issue by covici** [yo8192/fcron#29]
I was trying to use timezone of UTC for the whole crontab, at first I put before each command TZ=UTC but that did not work, so after reading the manual more carefully, I put the following line at the top of the file
!timezone(UTC)
but none of the jobs were run with UTC timezone, I also tried GMT .

I am using Linux operating system kernel 6.1.82 gentoo distribution.

Am I doing something wrong?

Thanks.

P.S. mailing list subscription returns host unknown.

**Comment by yo8192** [comment]
Thanks for pointing out the mailing list issue. Free.fr stopped that service, so they are no longer available. I've updated http://fcron.free.fr/contact.php.

What do you mean they were not run in the UTC timezone? do you mean they were not scheduled in the UTC timezone, or do you mean the `TZ` env var wasn't set to UTC within the job (if whatever you run checks that) ?

Please provide:
* the (optionally redacted) fcrontab file you use, e.g. the output of `fcrontab -l` (or specify the right user)
* your timezone, e.g. the output of `date` and of `ls -l /etc/localtime`
* the output of `fcrondyn -x ls` (optionally redacted)
* and what version of fcron you use (or whether you use the latest from github).

In the meantime, here is what I just tried, keeping in mind I am in timezone BST, so that's UTC+1:

```
$ fcrontab -l
2024-05-29 17:38:52  INFO listing user's fcrontab
!timezone(UTC)
40 16 * * * echo "16:40 UTC"

$ sudo fcrondyn -x ls
ID   |USER     |SCHEDULE           |CMD
1    |user     |2024-05-29 17:40:00|echo "16:40 UTC"
```
As you can see, the job was scheduled at 16:40 UTC, which is 17:40 BST, so all works as expected.

**Comment by yo8192** [comment]
Fair enough, I'll close this one then.
